name: CD

on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy env file
        run: cp $GITHUB_ENV $GITHUB_WORKSPACE/.env
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
